config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :properties do
    resources :bookings, only: [:index, :new, :create]
  end

  resources :bookings, only: [:show, :destroy] do
    resources :reviews, only: [:new, :create, :edit, :update]
  end

  resources :reviews, only: [:destroy]

  resources :users, only: [:show] do
    get "dashboard", to: "users#dashboard"
    get "bookings", to: "users#bookings"
    get "properties", to: "users#properties"
    get "reviews", to: "users#reviews"
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :property
  has_one :review, dependent: :destroy
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: [:show, :destroy]
  before_action :find_property, only: [:index, :create, :new]

  def index
    @booking = Booking.where(user: @property.user)
  end

  def show
    @length = @booking.end_date - @booking.start_date
    @total_price = @booking.property.price * @length
    @property = @booking.property
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.property = @property
    @booking.user = current_user
    if @booking.save
      redirect_to user_dashboard_path(current_user)
      flash.alert = "You are staying at #{@property.name}!  "

    else
      render :new
    end
  end

  def destroy
    @booking.destroy
    redirect_to user_dashboard_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def find_property
    @property = Property.find(params[:property_id])
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end
end

app/views/bookings/_form.html.erb
  <%= simple_form_for [property, booking] do |f| %>
      <div class="d-flex justify-content-between">
        <%= f.input :start_date, html5: true %>
        <%= f.input :end_date, html5: true %>
      </div>
      <%= f.submit "Submit", {class: "btn btn-primary w-100 mb-2"} %>
  <% end %>

app/views/bookings/index.html.erb
<h2>Bookings for <%= @property.name %> <%= @property.property_type %></h2>
<div class="container">
  <% @property.bookings.each do |booking| %>
  <div class="host-booking-information-card">
    <div class="host-booking-card-product-infos-1">
      <% length_of_stay = booking.end_date - booking.start_date %>
      <% total_price = length_of_stay.to_i * @property.price %>
      <h3><%= booking.user.name %> · <%=@property.capacity%> guests · <%= length_of_stay.to_i %> nights</h3>
      <p><%= booking.user.email %></p>
    </div>
      <div class="host-booking-card-product-infos-2">
        <h4> <%=  booking.start_date %> to <%= booking.end_date %></h4>
        <h5> <%= number_to_currency(total_price, unit: "£", precision: 0) %> </h5>
      </div>
  </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="devise-form bg-info col-md-8 col-sm-10 mx-auto mt-3 py-3 rounded">
  <h2 class="text-center">Create a new booking for <span class="bg-success px-2 rounded text-info"><%= @property.name %></span></h2>

  <hr>

  <%= simple_form_for [@property, @booking] do |f| %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <%= f.submit "Submit", {class: "btn btn-primary w-100 mb-2"} %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <h1>Your Booking for <%= @booking.property.name %></h1>
    <div class="icons">
    <h4>Add a review</h4>
        <%= link_to new_booking_review_path(@booking) do %>
        <i class="fas fa-plus"></i>
        <% end %>
  </div>

  <% if @property.photos.attached? %>
    <%= render 'shared/img_carousel' %>
  <% end %>

  <div class="booking-info my-5 d-flex justify-content-between">
    <div class="dates">
      <h2>Check-in: <%= @booking.start_date %></h2>
      <h2>Check-out: <%= @booking.end_date %></h2>
    </div>
    <div class="price-info">
      <h3><%= number_to_currency(@total_price, unit: "£", precision: 0) %></h3>
      <p><%= number_to_currency(@booking.property.price, unit: "£", precision: 0) %> / night</p>
    </div>
  </div>

    <div class="booking-property-info">
      <div class="property-info border-bottom">
        <h5>Host: <%= @property.user.name %> </h5>
          <p> <strong> <%= @property.property_type %> </strong>-- Capacity: <%= @property.capacity %></p>
      </div>
      <div class="property-desctription mt-2">
        <%= @property.description %>
      </div>
    </div>


  </div>


</div>