config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :properties do
    resources :bookings, only: [:index, :new, :create]
  end

  resources :bookings, only: [:show, :destroy] do
    resources :reviews, only: [:new, :create, :edit, :update]
  end

  resources :reviews, only: [:destroy]

  resources :users, only: [:show] do
    get "dashboard", to: "users#dashboard"
    get "bookings", to: "users#bookings"
    get "properties", to: "users#properties"
    get "reviews", to: "users#reviews"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :properties
  has_many :reviews
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def properties
    @properties = @user.properties
    @properties_with_stars = @properties.map do |property|
      {property: property, average_rating: stars(property)[:average_rating], blank_stars: stars(property)[:blank_stars]}
    end
  end

  def bookings
    @bookings = @user.bookings
  end

  def dashboard
    @bookings = @user.bookings
    @properties = @user.properties
    @properties_with_stars = @properties.map do |property|
      {property: property, average_rating: stars(property)[:average_rating], blank_stars: stars(property)[:blank_stars]}
    end
    @reviews = @user.reviews
  end

  def reviews
    @reviews = @user.reviews
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def stars(property)
    ratings = []
    sum = 0
    property.reviews.each do |review|
      ratings << review.rating
    end
    ratings.each do |rating|
      sum += rating.to_i
    end
    unless ratings.empty?
      average_rating = sum/ratings.length
      blank_stars = 5 - average_rating.to_i
      return {average_rating: average_rating, blank_stars: blank_stars}
    end
    return {average_rating: nil, blank_stars: nil}
  end
end

app/views/users/_bookings.html.erb
<% @bookings.each do |booking| %>
  <%= link_to booking_path(booking) do %>
    <div class="property-booking-card mx-0 mb-3">
      <% if booking.property.photos.attached? %>
      <div class="property-booking-card-photo">
          <%= cl_image_tag booking.property.photos.first.key, height: 150, width: 200, crop: :fill %>
      </div>
      <% end %>
      <div class="property-booking-card-product-infos">
        <% length = booking.end_date - booking.start_date %>
        <% total_price = booking.property.price * length %>
        <h3>Your Booking for <%= booking.property.name %></h3>
        <h5>Check-in: <%= booking.start_date %> </h5>
        <h5><%= booking.property.capacity%> guests · <%=booking.property.property_type %> · <%= number_to_currency(total_price, unit: "£", precision: 0) %> total · <%= number_to_currency(booking.property.price, unit: "£", precision: 0) %>/night</h5>
      </div>
    </div>
  <% end %>
<% end %>


  <!-- Modal -->
  <!-- <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Cancelling this booking without 48hr notice will cost you your deposit!
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Cancel Booking</button>
        </div>
      </div>
    </div>
  </div>

</div>
 -->

app/views/users/_properties.html.erb
<div class="icons">
  <h3>Add a property</h3>
      <%= link_to new_property_path(@property) do %>
      <i class="fas fa-plus"></i>
      <% end %>
</div>
<% @properties_with_stars.each do |property| %>
  <%= link_to property_path(property[:property]) do %>
    <div class="user-property-card mx-0">
      <% if property[:property].photos.attached? %>
        <div class="user-property-card-photo"><%= cl_image_tag property[:property].photos[0].key, height: 150, width: 200, crop: :fill %>
        </div>
      <% end %>
      <div class="user-property-card-info">
        <div class="user-property-card-top-row">
          <div class="user-property-card-title">
          <h3><%= property[:property].name%> </h3>
            <% unless property[:average_rating].nil? %>
              <p> <% property[:average_rating].times do %>
                <i class="fas fa-star"></i>
              <% end %>
              <% property[:blank_stars].times do %>
                <i class="far fa-star"></i>
              <% end %>
            <% end %>
            </p>
          </div>

          <div class="icons">
            <%= link_to edit_property_path(property[:property]) do %>
              <i class="fas fa-edit"></i>
            <% end %>
            <%= link_to property_path(property[:property]), method: :delete, data:
              { confirm: 'Are you certain you want to delete this?' } do %>
              <i class="fas fa-trash"></i>
            <% end %>
          </div>

        </div>
        <h5><%= property[:property].capacity%> guests · <%=property[:property].property_type %> · <%= number_to_currency(property[:property].price, unit: "£", precision: 0) %>/night</h5>
        <p> <%= property[:property].description.capitalize %></p>
      </div>
    </div>
  <% end %>
<% end %>






      <!-- <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
        Delete Property
      </button> -->

<!-- <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title-properties" id="exampleModalLabel">Are you sure?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body-properties">
          Deleting this property will erase all current bookings!
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary"><%#= link_to "Delete Property", properties_path(property), method: :delete %></button>
        </div>
      </div>
    </div>
  </div>

</div>
 -->

app/views/users/_reviews.html.erb
<% @reviews.each do |review| %>
  <div class="user-review-card mx-0 mb-3">
    <% if review.booking.property.photos.attached? %>
      <div class="user-review-card-photo">
        <%= cl_image_tag review.booking.property.photos.first.key, height: 150, width: 200, crop: :fill %>
      </div>
    <% end %>
    <div class="user-review-card-info justify-content-between flex-grow-1">
      <div class="user-review-card-info-text">
        <h3><%= review.booking.property.name %></h3>
        <p><%= review.content.capitalize %></p>
        <div class="review-rating">
          <% review.rating.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          <% blank_stars = 5 - review.rating %>
          <% blank_stars.times do %>
            <i class="far fa-star"></i>
          <% end %>
        </div>
      </div>
      <div class="booking-info">
        <div class="info-price-date">
          <% length = review.booking.end_date - review.booking.start_date %>
          <% total_price = review.booking.property.price * length %>
          <h4><%= review.booking.start_date %> - <%= review.booking.end_date %></h4>
          <h3><%= number_to_currency(total_price, unit: "£", precision: 0) %></h3>
          </div>
        <div class="icons-review">
          <%= link_to edit_booking_review_path(review.booking, review) do %>
            <i class="fas fa-edit"></i>
          <% end %>
          <%= link_to review_path(review), method: :delete, data:
            { confirm: 'Are you certain you want to delete this?' } do %>
            <i class="fas fa-trash"></i>
        <% end %>
      </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/dashboard.html.erb
<div class="container">
  <ul class="nav nav-tabs">
    <li class="tab active" id="tab-bookings"><a href="#">Bookings</a></li>
    <li class="tab" id="tab-properties"><a href="#">Properties</a></li>
    <li class="tab" id="tab-reviews"><a href="#">Reviews</a></li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="bookings">
      <%= render 'bookings' %>
    </div>
    <div class="tab-pane" id="properties">
      <%= render 'properties' %>
    </div>
    <div class="tab-pane" id="reviews">
      <%= render 'reviews' %>
    </div>
  </div>
</div>