config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :properties do
    resources :bookings, only: [:index, :new, :create]
  end

  resources :bookings, only: [:show, :destroy] do
    resources :reviews, only: [:new, :create, :edit, :update]
  end

  resources :reviews, only: [:destroy]

  resources :users, only: [:show] do
    get "dashboard", to: "users#dashboard"
    get "bookings", to: "users#bookings"
    get "properties", to: "users#properties"
    get "reviews", to: "users#reviews"
  end
end

app/views/shared/_flash.html.erb
<div class="flash flash-success alert alert-dismissible fade show" role="alert">
  <span><strong>Congratulations!</strong> 🎉 <%= value + " " %></span>
  <a data-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>

app/views/shared/_footer.html.erb
<div class="footer text-center d-flex justify-content-center align-items-center mt-5">
  <div class="share-icons">
  </div>
  <p>© 1979 - 2020 AirBnB | By Bild</p>
</div>

app/views/shared/_img_carousel.html.erb
<% if @property.photos.length > 1  %>
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <% @property.photos.each_with_index do |photo, index| %>
        <div class="carousel-item text-center <%=index == 0 ? 'active' : ''  %>">
          <%= cl_image_tag photo.key, height: 400, crop: :fill, :class => "" %>
        </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
<% else %>
  <div class="photo-container text-center">
    <%= cl_image_tag @property.photos[0].key, height: 400, crop: :fill, :class => "" %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm bg-transparent">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png"%>
  <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Dashboard", user_dashboard_path(current_user), class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item active">
          <%= link_to "+ List a property", new_property_path, class: "text-dark nav-link btn btn-primary mx-3" %>
        </li>
      <li class="nav-item">
        <%= image_tag "https://media-exp1.licdn.com/dms/image/C5603AQGKfVGsdtKTTg/profile-displayphoto-shrink_200_200/0?e=1595462400&v=beta&t=aqpFZpmw5S5vgS3lXFvP3xgbrSGf2vdZ9Vd1e9zNmr4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      </li>
    </ul>
  </div>
</div>